### ISSUE TITLE
Add `artifacts` publish for `Github Actions` builds

### ISSUE THREAD

**Issue by wopox1337** [alliedmodders/amxmodx#1009]
It's a necessity for convenience.

**Comment by ShootingKing-AM** [comment]
I think there is some sort of misunderstanding here, build artifacts appear in GitHub actions page like this, post successful build, 

<img src=https://user-images.githubusercontent.com/16109154/103645952-223c6880-4f59-11eb-8268-8dca6937b5f9.png>

It is much easier to trust and test these artifacts rather than setup local dev env with multiple OS/toolkit versions.

As a very concrete example, when I proposed a fix for Issue https://github.com/alliedmodders/amxmodx/issues/988#issuecomment-918426637 . I was forced to upload binaries, and other people for testing had to download and run those binaries, which pose much more security implications than transparant multi-os/toolkit GitHub actions artifacts.

**Comment by dvander** [comment]
I still view this as a security issue, because it's under the purview of our repository, and it's unreviewed code.

But I'll let @asherkin comment and if he's okay with it, we can do it.

**Comment by asherkin** [comment]
@dvander I think we could be OK here as long as it was only enabled for PRs and not regular branch builds, and clearly identified separately from a normal snapshot build as you've said. GitHub Actions do require manual approval before workflows are run for first-time contributors, we can make that required for all external contributors if desired.

> As a very concrete example, when I proposed a fix for Issue [#988 (comment)](https://github.com/alliedmodders/amxmodx/issues/988#issuecomment-918426637) . I was forced to upload binaries, and other people for testing had to download and run those binaries, which pose much more security implications than transparant multi-os/toolkit GitHub actions artifacts.

@ShootingKing-AM It doesn't look like anyone actually asked for those binaries, so you were hardly forced, but I agree that it's much easier to trust binaries from the CI system - but dvander's point is that those binaries aren't *actually trusted*, which is an important consideration, and GitHub doesn't let us warn people about that easily.

I'd expect anyone who actually wanted to test a PR who should be testing a PR to both be capable of building it themselves and actually desire to build it themselves - in order to have debug symbols and be able to tweak it if required. So my view here is that it isn't too harmful to enable, but it'll need some work done to label the builds appropriately, and that's probably best made as a PR to the actions config and associated build files if it's something you'd like to see.

**Comment by dvander** [comment]
It's both.

Review speed is definitely a problem. Feel free to ping me if you've been waiting too long. And if we need to add new maintainers, that's a discussion we can totally have as well.
