### ISSUE TITLE
[Question] Why latest master commits are not being built for Windows and Mac?

### ISSUE THREAD

**Issue by rtxa** [alliedmodders/amxmodx#1068]
According to https://www.amxmodx.org/downloads-new.php?branch=master, some of the latest commits are not being built for Windows and Mac, with the exception of Linux. Is there something wrong with the automatic compiler which for some reason wasn't available? Can this be triggered manually? I'm just looking for testing the latest commits on my own PC.

![](https://imgur.com/piwPJRb.png)

**Comment by rtxa** [comment]
@SmileYzn

Well, technically, Github Actions for AMX Mod X is working well for Windows and Linux according to this: https://github.com/alliedmodders/amxmodx/actions/runs/2594723696 but artifacts are not available for download.

I tried in the past, years ago to clone the project, and I remember following all the steps and it didn't compile. Finally I get it compile somehow with some info I found on some old threads from the forum, but right now I'm in a fresh computer. I'm not sure I want to go through that burden again.

It would be nice if this gets fixed.

**Comment by pizzahut2** [comment]
@ShootingKing-AM Could you look into this issue please?

**Comment by ShootingKing-AM** [comment]
Prima facie, it looks like backend perl on buildbot was updated to latest stable 5.3 (don't know which version of perl it had previously). There were some breaking changes in perl like `@INC` directory not having the pwd for "require" and standard "helpers.pm" would not be shipped default etc.. 

If GitHub actions succeed then there is no issue with amxmodx code. Issue lies with the rolling-release workflow. You can compile it successfully locally yourself. (artifact's discussion here: https://github.com/alliedmodders/amxmodx/issues/1009)

Either have to downgrade perl or compensate those breaking changes with PR to https://github.com/alliedmodders/amxmodx/tree/master/support/buildbot 

Never used perl myself, so if there people who are used to perl they can make a PR.

**Comment by dvander** [comment]
I attempted a fix for this. It looks like it might be stuck at the packaging step. I'll check back tomorrow.

**Comment by dvander** [comment]
Windows builds should be working again. This was an obscure issue. (Perl, obscure?! Say it ain't so!)

The Archive::Tar module was failing to find a particular DLL. When I tried to install it from CPAN, the command failed. When I tried to build it from source that failed too. I took this opportunity to convert package.pl to Python. I didn't bother porting the GeoIP database packaging code since it hasn't been working for a long time anyway.

Anyone starting out a career in programming right now has missed the heyday of Perl by about 20 years. So these scripts are likely to get Pythonized as they get altered.
