### ISSUE TITLE
[DoD] client_print's displaying as "%s" in chat

### ISSUE THREAD

**Issue by diamond-optic** [alliedmodders/amxmodx#776]
Happening even on a completely fresh stock hlds + metamod + stock amxx. 'timeleft' 'nextmap' etc all just show "%s" output in the chat.

Updated my hlds yesterday, build now showing as Jul 24 2019 (8308). Then I updated my amxx to 5386 and this started happening. Reverted back to 5378 and it works fine. Issue starts after the change in 5380.

Day of Defeat
Metamod 1.21p38
Windows Server 2008 R2

Screenshot: https://imgur.com/g1mSagN

**Comment by WPMGPRoSToTeMa** [comment]
Do you use the latest client?

**Comment by diamond-optic** [comment]
Updated my client yesterday as well. Verified integrity of game files today. But for the sake of trying everything, I just renamed the folder and it is currently downloading a fresh copy of the client

**Comment by Arkshine** [comment]
It's a side-effect of  #763.

https://github.com/ValveSoftware/halflife/issues/2611#issuecomment-546546158
Dod doesn't support that.

I created a new issue : https://github.com/ValveSoftware/halflife/issues/2744

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine I hope we can use a hack with [`#Spec_PlayerItem`](https://github.com/WPMGPRoSToTeMa/ChatPrint/blob/93dd63cddbf8f170eef84bc423dc4a5a0d2fbfd6/ChatPrint.inc#L55) (expands to `%s1`) for unsupported mods.

**Comment by Arkshine** [comment]
Just tested with DoD, and it doesn't work on SayText and TextMsg.

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine I hope we can use a hack with [`#Spec_PlayerItem`](https://github.com/WPMGPRoSToTeMa/ChatPrint/blob/93dd63cddbf8f170eef84bc423dc4a5a0d2fbfd6/ChatPrint.inc#L55) (expands to `%s1`) for unsupported mods.

**Comment by Arkshine** [comment]
@WPMGPRoSToTeMa 
 
Is `#Spec_PlayerItem` generic to HL1 games?
I don't know if localization is useful in console. Did you already see a plugin doing that?
Either way, It can wait another PR.

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine it is located in `valve/resource/valve_*.txt`, as I can see this file should be fallback for any mod, and also `#Spec_PlayerItem` should be expanded to `%s1` for any language. The problem is that `SayText` and `TextMsg` don't always support formatting, for example `SayText` in DoD takes only one string and looks like `TextMsg` in DoD takes only one string too for `print_console`.

What about replacing `TextMsg`+`print_console` with `svc_print` and other, I'm not sure that they behave exactly the same in all mods. For example, `TextMsg`+`print_center` behaves differently than `svc_centerprint` in DoD (`TextMsg`+`print_center` in DoD looks like `show_hudmessage`).

So I think it is better to leave it as it is now.

**Comment by Arkshine** [comment]
Safer to keep the original behavior if we don't know the result will be the same across all mods.

I don't have personally the time to check all HL1 mods. However, I don't mind adding a rule for a specific mod if someone provides it. 

That's said, we cover the official mods which represents 98.94% of servers. 
Actually, just tested Adrenaline Gamer (99.35% with it) and it works fine. I'm pretty sure that most of HL1 non-official mods supports format string by default. This feature was just removed on official mods before (actually only on CS?).
