### ISSUE TITLE
Crash in amxx ??

### ISSUE THREAD

**Issue by Karaulov** [alliedmodders/amxmodx#797]
[crash-2019-11-19_15-13-17.log](https://github.com/alliedmodders/amxmodx/files/3863730/crash-2019-11-19_15-13-17.log)

After every map change - crash.

**Comment by Karaulov** [comment]
After disable flag manager, i got next crash:

[crash-2019-11-19_15-30-54.log](https://github.com/alliedmodders/amxmodx/files/3863772/crash-2019-11-19_15-30-54.log)

**Comment by Karaulov** [comment]
sv_rehlds_send_mapcycle 1 can cause this crashes ?

**Comment by xLeviNx** [comment]
Need more information on this. 

AMXX version, metamod version, listed plugins, etc. Do you not use the template? How do you expect others to help you if you provide minimal information. Your crash log provides nothing.

**Comment by Karaulov** [comment]
@xLeviNx Problem in sv_rehlds_send_mapcycle, this not amxx crash i close it.

@xLeviNx need add to AMXX cmd "amx_github" for generate github issue template))))

**Comment by xLeviNx** [comment]
@Karaulov - For future reference, when you open the issue and see the details below, I really suggest you follow it in order to get help.

`# Help us help you
  - [ ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/amxmodx/issues).
  - [ ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: 
  * Game/AppID (with version if applicable): 
  * Current AMX Mod X version: 
  * Current Metamod version:
  - [ ] I have updated AMX Mod X to the [latest version](https://www.amxmodx.org/downloads.php) and it still happens.
  - [ ] I have updated AMX Mod X to the [latest snapshot](https://www.amxmodx.org/snapshots.php) and it still happens.
  - [ ] I have updated Metamod to the [latest version](https://www.amxmodx.org/downloads.php) and it still happens.

# Description


# Problematic Code (or Steps to Reproduce)
  ```PAWN
  // TODO(you): code here to reproduce the problem
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.
`

**Comment by Karaulov** [comment]
@xLeviNx no sorry, this not filled automatically via cmd command. if you can add cmd command to generate this template, do it!
