### ISSUE TITLE
Weird "TeamInfo" behavior change in 1.9/1.10

### ISSUE THREAD

**Issue by OciXCrom** [alliedmodders/amxmodx#936]
I have a custom colorchat include which caches team colors on higher player indexes (above 32):

```cpp
const CC_MAX_PLAYERS = 32

enum
{
	CC_COLOR_TEAM = CC_MAX_PLAYERS + 1,
	CC_COLOR_GREY,
	CC_COLOR_BLUE,
	CC_COLOR_RED
}

const CC_COLOR_WHITE = CC_COLOR_GREY

new iCacheList[] = { CC_COLOR_GREY, CC_COLOR_BLUE, CC_COLOR_RED }
new szCacheList[][] = { "", "CT", "TERRORIST" }
new CC_MSG_TEAMINFO = get_user_msgid("TeamInfo")

for(new i; i < sizeof(iCacheList); i++)
{
	engfunc(EngFunc_MessageBegin, MSG_INIT, CC_MSG_TEAMINFO, 0, 0)
	write_byte(iCacheList[i])
	write_string(szCacheList[i])
	message_end()
}

new iPlayers[CC_MAX_PLAYERS], iPnum
get_players(iPlayers, iPnum, CC_FILTERING_FLAGS) // "ch"

for(new iPlayer, i, j; i < iPnum; i++)
{
	iPlayer = iPlayers[i]

	for(j = 0; j < sizeof(iCacheList); j++)
	{
		message_begin(MSG_ONE, CC_MSG_TEAMINFO, _, iPlayer)
		write_byte(iCacheList[j])
		write_string(szCacheList[j])
		message_end()
	}
}
```

Now, when I try to send a grey/white message, everything is working as it should until I reconnect to the server. After reconnecting, the grey becomes red. All other colors function normally.

If I change the first enum member to +2, grey becomes blue, so there's some weird index shifting going on.
I added +20 in my fixed version just to be safe.

This is happening only in AMXX 1.9 & 1.10 (latest builds). On 1.8.2 it functions normally.

The full code can be found here - https://github.com/OciXCrom/CromChat/blob/master/cromchat.inc

**Comment by Arkshine** [comment]
https://www.amxmodx.org/api/amxmodx/client_print_color

**Comment by Arkshine** [comment]
1.9 is major release and it's expected to have minor behavior changes considering the vast amount of wanted features added.
Especially here, because there is not much choice and there is no convention in red/blue position.

I'm pretty sure all the concerned custom includes have already their code updated to use the native if AMXX version > 1.8.2.
The native has been added in 2013!

That's said, thanks for pointing out this -- I agree some note should be added in the API Changes wiki page (if not done already, but I don't think it exists).

As side-note, don't hesitate to update the wiki page if you can/want and you think some information is missing.
