### ISSUE TITLE
Non-zero defaut chat time in nextmap.sma breaks functionality for some games

### ISSUE THREAD

**Issue by fysiks1** [alliedmodders/amxmodx#975]
In amxmodx-1.8.2, the default value for `chattime` is 0.0 when the mp_chattime cvar doesn't exist.  However, in 64327b8ddb8db2b2c27d52e09ce03ec0737ccf3a the default value was changed to 10.0.  This breaks map change functionality in games that don't have mp_chattime because we can't know how long the built-in delay is between intermission (event 30) and the normal map change functionality.  For example, in Opposing Forces, the server will change the map before `delayedChange()` is called due to it being delayed for 10 seconds.

**Comment by djearthquake** [comment]
```g_mp_chattime = get_cvar_pointer("mp_chattime") ? get_cvar_pointer("mp_chattime") : register_cvar("mp_chattime", "20")``` [If 'mp_chattime' is created when nonexistent, like on 'Opposing Force', it resolves this.](https://github.com/djearthquake/amxx/blob/main/scripting/gearbox/nextmap%2B.sma) Changing float times on a null pointer won't create a "delayedChange" task. That is why we hear timeleft count down. We play for 2 more minutes. Next the changelevel is based off mapcycle instead of map we voted for. "delayedChange" I recommend clamping as fail-safe. ```floatclamp(chattime,1.0,122.0)```

**Comment by fysiks1** [comment]
@djearthquake simply creating the cvar doesn't actually fix anything because the server or a plugin would need to implement the mp_chattime functionality (which I'm not sure is possible for all games).

**Comment by djearthquake** [comment]
All mods have it except base Half-Life. **Final Stats** from  **Opposing Force Capture The Flag** is restored. There's no functionality to implement. There's 2 min to spare really once time shows as 0.
![Final op4ctf stats are back](https://user-images.githubusercontent.com/6540695/128756583-405131ff-cc5b-4dad-a125-54b14d861650.jpg)
